- name: Kreiraj folder za aplikaciju na ciljnoj mašini
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: Kopiraj kod aplikacije na ciljnu mašinu
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../"
    dest: "{{ app_dir }}"
    mode: preserve

- name: Generiši .env fajl iz templejta
  ansible.builtin.template:
    src: env.j2
    dest: "{{ app_dir }}/.env"
    mode: '0600'

- name: Pokreni aplikaciju komandom docker compose up
  ansible.builtin.shell:
    cmd: docker compose up --build -d
    chdir: "{{ app_dir }}"
